spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://localhost:5433/otp_auth
    username: postgres
    password: password@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.tandem.chatservice: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG

security:
  key: de94bba406d14d40a16abfd50179d6ac